#Titanic Project on Github
#eih2nn

install.packages("tidyverse") # Download library; (only required once)
library(tidyverse) # Load the core tidyverse packages: ggplot2, tibble, 
# tidyr, readr, purrr, and dplyr
library(ggplot2)

#Read in files:
train <- read_csv("train.csv") #Read in the comma separated value data file for training the model
test <- read_csv("test.csv") #Read in the csv data file for testing the model
gender <- read_csv("gender_submission.csv") #Read in the csv data file for example submission

#Change categorical variables in training set:
train$Survived <- factor(train$Survived) # Make Survived categorical
train$Pclass <- factor(train$Pclass) # Make Pclass categorical
train$Embarked <- factor(train$Embarked) # Make Embarked categorical

#Change categorical variables in testing set:
test$Pclass <- factor(test$Pclass) # Make Pclass categorical
test$Embarked <- factor(test$Embarked) # Make Embarked categorical

#Train logistric regression model
train.lg1 <- glm(Survived ~ .-(PassengerId+Name+Ticket+Fare+Cabin), data=train, family = "binomial") 
summary(train.lg1) #Summarize the values generated by lm

train.lg2 <- glm(Survived~Sex+Age+Pclass,data=train, family = "binomial")
summary(train.lg2)

# Let's try the full model on the prediction set
probs <- as.vector(predict(train.lg2,newdata=test, type="response"))
preds <- rep(0,418)  # Initialize prediction vector
preds[probs>0.5] <- 1 # p>0.5 -> 1
preds

#Add prediction column to test set
test["Survived"] <- NA
test$Survived <- preds
test_survived <- test[,c("PassengerId","Survived")]

write.table(test_survived, file = "eih2nn_titanic1.csv", row.names=F, sep=",")

preds1 <- read_csv("eih2nn_titanic1.csv") #Read in the comma separated value data file for predictions