#Titanic Project on Github
#eih2nn

install.packages("tidyverse") #Download library; (only required once)
library(tidyverse) #Load the core tidyverse packages: ggplot2, tibble, tidyr, readr, purrr, and dplyr

#Read in files:
train <- read_csv("train.csv") #Read in the comma separated value data file for training the model
test <- read_csv("test.csv") #Read in the csv data file for testing the model

#Change categorical variables in training set:
train$Survived <- factor(train$Survived) # Make Survived categorical
train$Pclass <- factor(train$Pclass) # Make Pclass categorical
train$Embarked <- factor(train$Embarked) # Make Embarked categorical

#Change categorical variables in testing set:
test$Pclass <- factor(test$Pclass) # Make Pclass categorical
test$Embarked <- factor(test$Embarked) # Make Embarked categorical

#Train logistic regression model using everything that might be helpful 
#Remove names, cabins, ticket, and fare (since this last one is too similar to class)
train.lg1 <- glm(Survived ~ .-(PassengerId+Name+Ticket+Fare+Cabin), data=train, family = "binomial") 
summary(train.lg1) #Summarize the values generated by glm
#Output: 
#Coefficients:
#               Estimate Std. Error z value Pr(>|z|)    
#  (Intercept)  4.62467    0.89055   5.193 2.07e-07 ***
#  Pclass2     -0.04389    0.82171  -0.053  0.95740    
#  Pclass3     -1.62822    0.90932  -1.791  0.07336 .  
#  Sexmale     -2.91751    0.50252  -5.806 6.41e-09 ***
#  Age         -0.04032    0.01474  -2.736  0.00622 ** 
# ... (all other variables have no significance)

#Try with just sex/gender, age, and class
train.lg2 <- glm(Survived~Sex+Age+Pclass,data=train, family = "binomial")
summary(train.lg2)
#Output: 
#Coefficients:
#               Estimate Std. Error z value Pr(>|z|)    
#(Intercept)    3.777013   0.401123   9.416  < 2e-16 ***
#  Sexmale     -2.522781   0.207391 -12.164  < 2e-16 ***
#  Age         -0.036985   0.007656  -4.831 1.36e-06 ***
#  Pclass2     -1.309799   0.278066  -4.710 2.47e-06 ***
#  Pclass3     -2.580625   0.281442  -9.169  < 2e-16 ***

#Use the most recent model for predictions on the test set
probs <- as.vector(predict(train.lg2,newdata=test, type="response"))
preds <- rep(0,418)  # Initialize prediction vector
preds[probs>0.5] <- 1 # p>0.5 -> 1
preds #Appears to have worked, as all outuput is in 1s and 0s

#Add prediction column to test set
test["Survived"] <- NA
test$Survived <- preds #Fill in values generated from prediction above
test_survived <- test[,c("PassengerId","Survived")] #Select only the necessary columns and assign to new df

write.table(test_survived, file = "eih2nn_titanic1.csv", row.names=F, sep=",") #Write out to a csv

preds1 <- read_csv("eih2nn_titanic1.csv") #Read in the comma separated value data file (just to check)